# Generated by Django 2.0.3 on 2018-03-19 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_RESCATE', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
